version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3"

sphinx:
  configuration: docs/conf.py

python:
  install:
    - requirements: requirements.txt
  system_packages: false

# Build PDF & ePub
formats:
  - epub
  - pdf

submodules:
  include: all
