version: 2

# Build PDF & ePub
formats:
  - epub
  - pdf

python:
  install:
    - requirements: requirements.txt
  system_packages: false

submodules:
  include: all

build:
  os: ubuntu-20.04
  tools:
    python: "3"
  jobs:
    post_checkout:
      - bash scripts/prepare_manpages_with_defaults.sh
