version: 2

# Build PDF & ePub
formats:
  - epub
  - pdf

python:
  install:
    - requirements: requirements.txt
  system_packages: false

submodules:
  include: all

build:
  os: ubuntu-20.04
  tools:
    python: "3"
  jobs:
    post_build:
      - bash scripts/use_defaults_for_manpages.sh
      #- echo `pwd`
      #- echo `ls -al source/_build/html/manpages`
